### ISSUE TITLE
Wifi support

### ISSUE THREAD

**Issue by swampmonster** [lazar89nis/Chorus-RF-Laptimer-iOS#1]
Hi.

I was curious if there was any interest in merging code to enable wifi support in the app.
My main objective would be to support the tcp/udp modes available in chorus32 but i
think it should also work for the original chorus project.

I'd be happy to have a go at contributing code for this if there's a chance of getting it merged.

**Comment by lazar89nis** [comment]
Hi @swampmonster,
Thanks for showing interest in helping with iOS project. It already has WiFi communication implemented. I never had time to look at chorus32 project to see if there is any difference but feel free to contribute to the project and make changes.

**Comment by swampmonster** [comment]
The API is to talk to the system is exactly the same as far as im aware.
I must be blind cause i only saw bluetooth as an option but i'll go look again :)

**Comment by lazar89nis** [comment]
On connection page you have switch that select if app is using bt or wifi module :)

**Comment by swampmonster** [comment]
Oh there it is. Nice :)
Ill check this out and see if everything works with chorus32!

**Comment by swampmonster** [comment]
Seems to mostly work. I get an API VERSION ERROR but it's still collecting data from the looks of it

**Comment by lazar89nis** [comment]
What version of API is chorus32 using?

**Comment by swampmonster** [comment]
V4

**Comment by lazar89nis** [comment]
Its version 6 here. I cant remember what are changes. I think you can try and just change constant to 4 and test it out. I think it will work just fine

**Comment by swampmonster** [comment]
I'll see if there are any major differences. But otherwise i'm thinking maybe adding something that differentiates the two systems. We could potentially add something to the version call in chorus32 that makes it clear that it's chorus32 and not normal chorus. That way your current code doesn't need to change and i can try writing some stuff that picks up anything chorus32 specific/different.

**Comment by voroshkov** [comment]
There are no major differences between v4  and v6.
See last 2 releases at https://github.com/voroshkov/Chorus-RF-Laptimer/releases

**Comment by lazar89nis** [comment]
That is great so it should work as it is.

**Comment by swampmonster** [comment]
I think we are going to just aim at bringing up chorus32 to v6 so you don’t have to have a workaround in your code. V5 was a debug flag which is no effort to add and @Smeat already had some code for V6 that he was going to look at again. So users can just ignore the version warning for now since it seems to work anyway.
